### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by ShaMan123** [asturur/test_builders#2]
We should configure process env in a better way (e.g. use a repo like dotenv because):
1. on windows for example the build cmd doesn't work
2. it's much easier to maintain
3. the replace plugin isn't good enough e.g (process.env[buildArg]) won't work

- https://www.npmjs.com/package/rollup-plugin-baked-env
- https://www.npmjs.com/package/rollup-plugin-inject-process-env
- https://www.npmjs.com/package/rollup-plugin-baked-env

**Comment by asturur** [comment]
yeah we can tweak but for starting is good enough.
I'm sure those are things that people solved already with different plugins.

Important is that there is backed the functionality for
- dead code removal
- tree shaking
- output more than one configuration, or support easily more config files

The rest are details
